import { physics } from './physicsEngine.js';
import { escapeHTML } from './utils.js';
import { renderGraph, bindGraphs } from './graphEngine.js';

const definitions = {
  projectile: { title:'Projectile Motion', topic:'Mechanics', engine:'projectile', fields:[['v','Initial speed','m s⁻¹',10,0,100],['angle','Launch angle','°',45,0,90],['gravity','Gravity','m s⁻²',9.81,1,25],['height','Initial height','m',0,0,100]], formula:'R = vₓt; y = h + vᵧt − ½gt²', mistakes:'Using degrees as radians or forgetting initial height.', lesson:'kinematics', graph:{id:'trajectory',title:'Projectile trajectory',x:'Horizontal distance',y:'Height',fn:x=>Math.max(0,8*x-.08*x*x)} },
  newton: { title:'Newton’s Second Law',topic:'Forces',engine:'newton',fields:[['force','Net force','N',10,-100,100],['mass','Mass','kg',2,.1,100]],formula:'F = ma',mistakes:'Using mass in grams rather than kilograms.',lesson:'forces',graph:{id:'velocity',title:'Velocity–time',x:'Time',y:'Velocity',fn:x=>x*.5} },
  energy: { title:'Kinetic & Potential Energy',topic:'Energy',engine:'energy',fields:[['mass','Mass','kg',1,.1,100],['height','Height','m',5,0,100],['velocity','Velocity','m s⁻¹',5,0,100],['gravity','Gravity','m s⁻²',9.81,1,25]],formula:'Eₖ = ½mv²; Eₚ = mgh',mistakes:'Confusing gravitational potential energy with total energy.',lesson:'energy',graph:{id:'energy',title:'Energy profile',x:'Position',y:'Energy',fn:x=>x*.5} },
  shm: {title:'Mass-Spring SHM',topic:'Waves',engine:'shm',fields:[['mass','Mass','kg',1,.1,20],['k','Spring constant','N m⁻¹',20,.1,200],['amplitude','Amplitude','m',1,.01,10]],formula:'T = 2π√(m/k)',mistakes:'Using amplitude in the period equation.',lesson:'simple-harmonic-motion',graph:{id:'shm',title:'Displacement–time',x:'Time',y:'Displacement',fn:x=>Math.sin(x*.3)*3}},
  'electric-field':{title:'Electric Field',topic:'Fields',engine:'coulomb',fields:[['q1','Source charge','C',1,-10,10],['q2','Test charge','C',1,-10,10],['r','Separation','m',1,.01,100]],formula:'F = kq₁q₂/r²',mistakes:'Forgetting that force direction depends on charge sign.',lesson:'electric-fields',graph:{id:'field',title:'Field strength–distance',x:'Distance',y:'Force',fn:x=>20/(x+4)}},
  'magnetic-force':{title:'Magnetic Force',topic:'Fields',engine:'magnetic',fields:[['B','Flux density','T',1,0,10],['q','Charge','C',1,-10,10],['v','Speed','m s⁻¹',10,0,100],['angle','Angle','°',90,0,180]],formula:'F = Bqv sinθ',mistakes:'Forgetting the sine factor.',lesson:'magnetic-fields',graph:{id:'magnetic',title:'Force–angle',x:'Angle',y:'Force',fn:x=>Math.sin(x*.05)*5}},
  'gas-law':{title:'Ideal Gas Law',topic:'Thermal',engine:'gas',fields:[['n','Amount','mol',1,.01,20],['T','Temperature','K',300,1,1000],['V','Volume','m³',1,.001,100]],formula:'PV = nRT',mistakes:'Using Celsius instead of kelvin.',lesson:'gas-laws',graph:{id:'gas',title:'Pressure–volume',x:'Volume',y:'Pressure',fn:x=>30/(x+4)}},
  'photon-energy':{title:'Photon Energy',topic:'Quantum',engine:'photon',fields:[['f','Frequency','Hz',1e14,0,1e16]],formula:'E = hf',mistakes:'Mixing wavelength and frequency units.',lesson:'quantum-physics',graph:{id:'photon',title:'Energy–frequency',x:'Frequency',y:'Energy',fn:x=>x*.2}},
  'radioactive-decay':{title:'Radioactive Decay',topic:'Nuclear',engine:'decay',fields:[['N0','Initial nuclei','nuclei',100,1,10000],['halfLife','Half-life','s',5,.01,1000],['time','Time','s',5,0,10000]],formula:'N = N₀(½)^(t/T½)',mistakes:'Adding half-lives instead of halving repeatedly.',lesson:'nuclear-physics',graph:{id:'decay',title:'Nuclei–time',x:'Time',y:'Nuclei',fn:x=>18*Math.exp(-x/26)}},
  'lorentz-factor':{title:'Lorentz Factor',topic:'Relativity',engine:'relativity',fields:[['v','Velocity','m s⁻¹',1e8,0,2.99e8]],formula:'γ = 1 / √(1 − v²/c²)',mistakes:'Using a velocity equal to or greater than c.',lesson:'relativity',graph:{id:'relativity',title:'Lorentz factor–velocity',x:'Velocity',y:'γ',fn:x=>1/Math.sqrt(Math.max(.01,1-(x/105)**2))}}
};
const presets={Earth:{gravity:9.81},Moon:{gravity:1.62},Mars:{gravity:3.71},Easy:{v:5,force:5,mass:1},Medium:{v:10,force:10,mass:2},Hard:{v:30,force:40,mass:5}};
const card=sim=>`<a class="module-card" href="/simulations/${sim}" data-route><span class="tag">${definitions[sim].topic} · SL + HL</span><h3>${definitions[sim].title}</h3><p>Interactive deterministic model with live calculations and graph panel.</p><span class="open-module">Open lab →</span></a>`;
export const catalogue=()=>`<section class="page"><p class="eyebrow">SIMULATION STUDIO</p><h1>Model the physics.</h1><div class="module-grid">${Object.keys(definitions).map(card).join('')}</div></section>`;
export const detail=slug=>{const sim=definitions[slug];if(!sim)return '<section class="page"><h1>Simulation not found</h1></section>';return `<section class="page simulation-page"><a href="/simulations" data-route>← Simulation Studio</a><p class="eyebrow">${sim.topic} · SL + HL</p><h1>${sim.title}</h1><p class="page-lead">Explore a deterministic model with SI-unit controls and live calculated values.</p><div class="dash-grid"><section class="content-card"><h2>Controls</h2><form id="simForm" data-sim="${slug}">${sim.fields.map(([key,label,unit,value,min,max])=>`<label>${label} (${unit})<input type="range" name="${key}" min="${min}" max="${max}" step="any" value="${value}" aria-label="${label}"><input type="number" data-number="${key}" min="${min}" max="${max}" step="any" value="${value}"></label>`).join('')}<div><button class="button" type="button" data-play>Play</button><button class="outline" type="button" data-pause>Pause</button><button class="outline" type="reset">Reset</button><button class="outline" type="button" data-csv>Export CSV</button></div></form><div>${Object.keys(presets).map(name=>`<button class="text-button" data-preset="${name}">${name}</button>`).join(' · ')}</div></section><section id="simOutput" class="content-card" aria-live="polite"></section></div><section class="lesson-section"><h2>Graph panel</h2>${renderGraph(sim.graph)}</section><section class="lesson-section"><h2>Theory & exam connection</h2><p><b>Equation:</b> ${escapeHTML(sim.formula)}</p><p><b>Common mistake:</b> ${escapeHTML(sim.mistakes)}</p><p>IB tip: state assumptions, use SI units, and evaluate model limitations.</p><a href="/lesson/${sim.lesson}" data-route>Open related lesson →</a></section></section>`};
const values=form=>Object.fromEntries([...form.querySelectorAll('input[type=range]')].map(input=>[input.name,Number(input.value)]));
export function bindStudio(){const form=document.querySelector('#simForm');if(!form)return;const sim=definitions[form.dataset.sim];let playing=false;let raf;const output=document.querySelector('#simOutput');const update=()=>{const input=values(form);const invalid=[...form.querySelectorAll('[data-number]')].some(number=>{const value=Number(number.value);return !Number.isFinite(value)||value<Number(number.min)||value>Number(number.max)});const result=!invalid&&physics[sim.engine](input);output.innerHTML=result?`<h2>Live values</h2><dl>${Object.entries(result).map(([key,value])=>`<dt>${escapeHTML(key)}</dt><dd>${Number(value).toPrecision(5)}</dd>`).join('')}</dl>`:'<p role="alert">Enter a physically valid value within the shown range.</p>';return {input,result}};const animate=()=>{if(!playing)return;update();raf=requestAnimationFrame(animate)};form.querySelectorAll('input[type=range]').forEach(range=>range.addEventListener('input',()=>{form.querySelector(`[data-number="${range.name}"]`).value=range.value;update()}));form.querySelectorAll('[data-number]').forEach(number=>number.addEventListener('input',()=>{const range=form.querySelector(`[name="${number.dataset.number}"]`);const value=Math.min(Number(range.max),Math.max(Number(range.min),Number(number.value)));if(Number.isFinite(value)){range.value=value;number.value=value}update()}));form.addEventListener('reset',()=>setTimeout(update));form.querySelector('[data-play]').onclick=()=>{playing=true;animate()};form.querySelector('[data-pause]').onclick=()=>{playing=false;cancelAnimationFrame(raf)};document.querySelectorAll('[data-preset]').forEach(button=>button.onclick=()=>{Object.entries(presets[button.dataset.preset]).forEach(([key,value])=>{const input=form.querySelector(`[name="${key}"]`);if(input){input.value=value;form.querySelector(`[data-number="${key}"]`).value=value}});update()});form.querySelector('[data-csv]').onclick=()=>{const {input,result}=update();const csv=Object.entries({...input,...result}).map(([key,value])=>`${key},${value}`).join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));link.download=`${form.dataset.sim}.csv`;link.click();URL.revokeObjectURL(link.href)};update();const cleanupGraphs=bindGraphs();return()=>{playing=false;cancelAnimationFrame(raf);cleanupGraphs?.()}}
